2025-01-21 14:47:45,180 - root - INFO - FPL data pipeline started...
2025-01-21 14:58:37,710 - root - INFO - FPL data pipeline finished
2025-01-21 15:04:25,048 - root - INFO - FPL data pipeline started...
2025-01-21 15:09:37,792 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-01-21 15:30:18,038 - root - INFO - FPL data pipeline started...
2025-01-21 15:30:19,364 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-01-21 15:31:38,287 - root - INFO - FPL data pipeline started...
2025-01-21 15:36:36,256 - root - ERROR - Failed to run pipeline: There are unmatched rows in the understat data.
2025-01-21 15:44:06,659 - root - INFO - FPL data pipeline started...
2025-01-21 15:44:44,408 - root - INFO - FPL data pipeline started...
2025-01-21 15:47:17,285 - root - ERROR - Failed to run pipeline: [Errno 2] No such file or directory: ''
2025-01-21 15:48:53,984 - root - INFO - FPL data pipeline started...
2025-01-21 15:52:18,928 - root - ERROR - Failed to run pipeline: [Errno 2] No such file or directory: ''
2025-01-21 15:55:31,018 - root - INFO - FPL data pipeline started...
2025-01-21 15:56:16,638 - root - INFO - FPL data pipeline started...
2025-01-21 15:56:19,188 - root - INFO - FPL data pipeline finished
2025-01-21 16:04:42,212 - root - INFO - FPL data pipeline started...
2025-01-21 16:08:13,902 - root - INFO - FPL data pipeline finished
2025-01-21 16:11:42,085 - root - INFO - FPL data pipeline started...
2025-01-21 16:15:16,364 - root - INFO - FPL data pipeline finished
2025-01-21 16:18:54,306 - root - INFO - FPL data pipeline started...
2025-01-21 16:18:56,076 - root - ERROR - Failed to run pipeline: index 0 is out of bounds for axis 0 with size 0
2025-01-21 16:21:36,283 - root - INFO - FPL data pipeline started...
2025-01-21 16:21:38,129 - root - ERROR - Failed to run pipeline: index 0 is out of bounds for axis 0 with size 0
2025-01-21 16:22:17,340 - root - INFO - FPL data pipeline started...
2025-01-21 16:22:28,805 - root - INFO - FPL data pipeline started...
2025-01-21 16:25:54,951 - root - INFO - FPL data pipeline finished
2025-01-21 16:45:51,583 - root - INFO - FPL data pipeline started...
2025-01-21 16:49:20,383 - root - INFO - FPL data pipeline finished
2025-01-21 17:13:11,479 - root - INFO - FPL data pipeline started...
2025-01-21 17:24:46,449 - root - INFO - FPL data pipeline finished
2025-03-02 22:48:25,379 - root - INFO - FPL data pipeline started...
2025-03-02 22:51:13,960 - root - ERROR - Failed to run pipeline: 'str' object has no attribute 'spli'
2025-03-02 22:54:16,184 - root - INFO - FPL data pipeline started...
2025-03-02 22:54:18,589 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:05:21,449 - root - INFO - FPL data pipeline started...
2025-03-03 21:05:27,019 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TargetClosedError('Target page, context or browser has been closed')>
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
2025-03-03 21:05:38,592 - root - INFO - FPL data pipeline started...
2025-03-03 21:05:44,783 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:07:58,912 - root - INFO - FPL data pipeline started...
2025-03-03 21:08:00,581 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:10:07,289 - root - INFO - FPL data pipeline started...
2025-03-03 21:10:08,579 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:11:15,547 - root - INFO - FPL data pipeline started...
2025-03-03 21:11:16,976 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:12:30,512 - root - INFO - FPL data pipeline started...
2025-03-03 21:12:32,244 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:12:45,832 - root - INFO - FPL data pipeline started...
2025-03-03 21:12:47,081 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:13:30,257 - root - INFO - FPL data pipeline started...
2025-03-03 21:13:31,916 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:15:01,025 - root - INFO - FPL data pipeline started...
2025-03-03 21:15:02,338 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:16:16,877 - root - INFO - FPL data pipeline started...
2025-03-03 21:16:18,081 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:16:37,696 - root - INFO - FPL data pipeline started...
2025-03-03 21:16:39,276 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:17:25,267 - root - INFO - FPL data pipeline started...
2025-03-03 21:17:26,479 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:18:06,349 - root - INFO - FPL data pipeline started...
2025-03-03 21:18:07,978 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:23:42,408 - root - INFO - FPL data pipeline started...
2025-03-03 21:23:44,249 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:26:11,732 - root - INFO - FPL data pipeline started...
2025-03-03 21:26:14,461 - root - ERROR - Failed to run pipeline: Some players are missing from the players_df.
2025-03-03 21:28:07,858 - root - INFO - FPL data pipeline started...
2025-03-04 23:42:39,573 - root - INFO - FPL data pipeline started...
2025-03-04 23:50:38,358 - root - INFO - FPL data pipeline finished
2025-03-04 23:53:09,513 - root - INFO - FPL data pipeline started...
2025-03-04 23:56:07,565 - root - INFO - FPL data pipeline finished
2025-03-05 23:24:14,318 - root - INFO - FPL data pipeline started...
2025-03-05 23:24:26,092 - root - ERROR - Failed to run pipeline: '>=' not supported between instances of 'str' and 'int'
2025-03-05 23:26:03,320 - root - INFO - FPL data pipeline started...
2025-03-05 23:26:04,289 - root - ERROR - Failed to run pipeline: 'list' object has no attribute 'empty'
2025-03-05 23:26:32,036 - root - INFO - FPL data pipeline started...
2025-03-05 23:36:41,105 - root - INFO - FPL data pipeline started...
2025-03-05 23:37:02,106 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2594' coro=<Locator.inner_text() done, defined at /home/martin/.pyenv/versions/3.12.4/lib/python3.12/site-packages/playwright/_impl/_locator.py:442> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "/home/martin/Documents/GitHub/fpl-prediction/backend/pipeline.py", line 465, in <module>
    main()
  File "/home/martin/Documents/GitHub/fpl-prediction/backend/pipeline.py", line 434, in main
    scrape_understat_data()
  File "/home/martin/Documents/GitHub/fpl-prediction/backend/scraper.py", line 195, in scrape_understat_data
    run(playwright)
  File "/home/martin/Documents/GitHub/fpl-prediction/backend/scraper.py", line 154, in run
    player_game_df, player_game_id = get_data_from_players(table, rows, player_game_df, player_game_id, game_id, team)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/Documents/GitHub/fpl-prediction/backend/scraper.py", line 29, in get_data_from_players
    minutes = row.locator("td").nth(3).inner_text()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 16500, in inner_text
    self._sync(self._impl_obj.inner_text(timeout=timeout))
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 113, in _sync
    self._dispatcher_fiber.switch()
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/site-packages/playwright/sync_api/_context_manager.py", line 56, in greenlet_main
    self._loop.run_until_complete(self._connection.run_as_sync())
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/asyncio/base_events.py", line 1987, in _run_once
    handle._run()
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/site-packages/playwright/_impl/_locator.py", line 444, in inner_text
    return await self._frame.inner_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 618, in inner_text
    return await self._channel.send("innerText", locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 512, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 85, in inner_send
    callback = self._connection._send_message_to_server(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 327, in _send_message_to_server
    getattr(task, "__pw_stack_trace__", traceback.extract_stack()),
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/traceback.py", line 232, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/traceback.py", line 395, in extract
    return klass._extract_from_extended_frame_gen(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/traceback.py", line 430, in _extract_from_extended_frame_gen
    result.append(FrameSummary(
                  ^^^^^^^^^^^^^
  File "/home/martin/.pyenv/versions/3.12.4/lib/python3.12/traceback.py", line 265, in __init__
    def __init__(self, filename, lineno, name, *, lookup_line=True,
    
KeyboardInterrupt
2025-03-05 23:37:30,983 - root - INFO - FPL data pipeline started...
2025-03-05 23:40:14,564 - root - INFO - FPL data pipeline started...
2025-03-05 23:40:27,693 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TargetClosedError('Target page, context or browser has been closed')>
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
2025-03-05 23:41:18,290 - root - INFO - FPL data pipeline started...
2025-03-05 23:43:34,267 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TargetClosedError('Target page, context or browser has been closed')>
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
2025-03-05 23:45:58,956 - root - INFO - FPL data pipeline started...
2025-03-05 23:46:38,743 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TargetClosedError('Target page, context or browser has been closed')>
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
2025-03-05 23:47:22,130 - root - INFO - FPL data pipeline started...
2025-03-05 23:49:34,212 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TargetClosedError('Target page, context or browser has been closed')>
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
2025-03-05 23:53:05,945 - root - INFO - FPL data pipeline started...
2025-03-05 23:53:06,655 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=TargetClosedError('Target page, context or browser has been closed')>
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
2025-03-05 23:53:17,308 - root - INFO - FPL data pipeline started...
2025-03-07 21:18:50,892 - root - INFO - FPL data pipeline started...
2025-03-07 21:19:06,277 - root - ERROR - Failed to run pipeline: name 'player_game_df' is not defined
2025-03-07 21:21:40,650 - root - INFO - FPL data pipeline started...
2025-03-07 21:21:44,855 - root - ERROR - Failed to run pipeline: name 'player_game_df' is not defined
2025-03-07 21:24:48,207 - root - INFO - FPL data pipeline started...
2025-03-07 21:24:51,895 - root - ERROR - Failed to run pipeline: name 'game_df' is not defined
2025-03-07 21:25:22,867 - root - INFO - FPL data pipeline started...
2025-03-08 12:27:29,277 - root - INFO - FPL data pipeline started...
2025-03-08 12:28:33,293 - root - ERROR - Failed to run pipeline: cannot access local variable 'last_game_number' where it is not associated with a value
2025-03-08 12:44:18,446 - root - INFO - FPL data pipeline started...
2025-03-08 12:44:18,645 - root - ERROR - Failed to run pipeline: cannot access local variable 'game_number' where it is not associated with a value
2025-03-08 12:47:32,629 - root - INFO - FPL data pipeline started...
2025-03-08 12:50:32,182 - root - INFO - FPL data pipeline started...
2025-03-08 12:56:31,815 - root - ERROR - Failed to run pipeline: name 'value' is not defined
2025-03-08 13:00:06,200 - root - INFO - FPL data pipeline started...
2025-03-08 13:02:57,044 - root - ERROR - Failed to run pipeline: name 'value' is not defined
2025-03-08 13:04:32,399 - root - INFO - FPL data pipeline started...
2025-03-08 13:07:24,116 - root - ERROR - Failed to run pipeline: 'dict' object has no attribute 'home'
2025-03-08 13:09:04,855 - root - INFO - FPL data pipeline started...
2025-03-08 13:12:00,951 - root - INFO - FPL data pipeline finished
2025-03-08 13:28:03,663 - root - INFO - FPL data pipeline started...
2025-03-08 13:31:03,934 - root - INFO - FPL data pipeline finished
2025-03-08 13:35:04,088 - root - INFO - FPL data pipeline started...
2025-03-08 13:38:00,107 - root - INFO - FPL data pipeline finished
2025-03-08 13:44:00,820 - root - INFO - FPL data pipeline started...
2025-03-08 13:46:54,789 - root - INFO - FPL data pipeline finished
2025-03-08 13:52:13,873 - root - INFO - FPL data pipeline started...
2025-03-08 13:55:06,484 - root - INFO - FPL data pipeline finished
2025-03-08 17:23:15,402 - root - INFO - FPL data pipeline started...
2025-03-08 17:24:12,082 - root - INFO - FPL data pipeline started...
2025-03-08 17:28:33,932 - root - ERROR - Failed to run pipeline: 'minutes'
2025-03-08 17:31:20,677 - root - INFO - FPL data pipeline started...
2025-03-08 17:31:56,011 - root - INFO - FPL data pipeline started...
2025-03-08 17:34:57,689 - root - INFO - FPL data pipeline finished
